name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install depends
      run: |
        sudo apt-get -y update
        sudo apt-get install -y build-essential wget libcurl4-openssl-dev ca-certificates cmake tree

    - name: mkdir
      run: mkdir out
    
    - name: cpp_curl
      run: |
        make cpp_curl
        ./out/cpp_curl https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz

    - name: optxcurl
      run: |
        make optxcurl
        ./out/optxcurl https://www.apple.com/itunes/download/win64

    - name: optxget
      run: |
        make optxget
        ./out/optxget https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz

    - name: followrel
      run: |
        make followrel
        ./out/followrel https://www.apple.com/itunes/download/win64

    - name: dirtree
      run: |
        tree
        ls -l