name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install depends
      run: |
        sudo apt-get -y update
        sudo apt-get install -y libcurl4-openssl-dev tree
    - name: make optxcurl
      run: make optxcurl
    - name: execut optxcurl
      run: |
        ./out/optxcurl https://www.apple.com/itunes/download/win64
        tree
        ls -l
    - name: make optxget
      run: make optxget
    - name: execute optxget
      run: ./out/optxget https://speed.hetzner.de/100MB.bin 100MB.bin