name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install depends
      run: |
        sudo apt-get -y update
        sudo apt-get install -y libcurl4-openssl-dev
    - name: make all
      run: make optxcurl
    # - name: execute followrel
    #   run: ./out/followrel https://www.apple.com/itunes/download/win64
    - name: execut optxcurl
      run: ./out/optxcurl https://www.apple.com/itunes/download/win64
